import { StyleSheet } from 'react-native';
import { theme } from '../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.textPrimary,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 16,
    color: theme.textSecondary,
    opacity: 0.8,
  },
  searchContainer: {
    flexDirection: 'row',
    padding: 20,
    paddingBottom: 10,
    alignItems: 'center',
    gap: 10,
  },
  searchInput: {
    flex: 1,
    height: 45,
    backgroundColor: theme.surface,
    borderRadius: 25,
    paddingHorizontal: 20,
    fontSize: 16,
    color: theme.textPrimary,
    borderWidth: 1,
    borderColor: theme.border,
  },
  portfolioButton: {
    backgroundColor: theme.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    elevation: 3,
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  portfolioButtonText: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  filtersContainer: {
    paddingHorizontal: 20,
    paddingBottom: 10,
    gap: 10,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  filterButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: theme.surface,
    borderRadius: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  filterButtonActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  filterButtonText: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '500',
  },
  filterButtonTextActive: {
    color: theme.textPrimary,
    fontWeight: '600',
  },
  advancedFilterButton: {
    backgroundColor: theme.surface,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: theme.border,
  },
  advancedFilterButtonText: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '500',
  },
  autoRefreshContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  autoRefreshLabel: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '500',
  },
  advancedFilters: {
    backgroundColor: theme.surface,
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 15,
  },
  filterGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
  },
  filterLabel: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '500',
    flex: 1,
  },
  sortButton: {
    backgroundColor: theme.background,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  sortButtonActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  sortButtonText: {
    color: theme.textSecondary,
    fontSize: 11,
    fontWeight: '500',
  },
  filterSlider: {
    flex: 2,
    height: 20,
    backgroundColor: theme.background,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.border,
  },
  filterSliderFill: {
    height: '100%',
    backgroundColor: theme.primary,
  },
  statsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: theme.surface,
    marginHorizontal: 20,
    marginBottom: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: theme.border,
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statLabel: {
    color: theme.textSecondary,
    fontSize: 11,
    fontWeight: '500',
    marginBottom: 3,
  },
  statValue: {
    color: theme.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
  },
  loadingText: {
    color: theme.textSecondary,
    fontSize: 16,
    fontWeight: '500',
  },
  assetItem: {
    backgroundColor: theme.surface,
    borderRadius: 15,
    padding: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  assetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  assetInfo: {
    flex: 1,
  },
  assetSymbol: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.textPrimary,
    marginBottom: 2,
  },
  assetType: {
    fontSize: 12,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  assetPrice: {
    alignItems: 'flex-end',
  },
  assetPriceText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.textPrimary,
    marginBottom: 2,
  },
  assetChangeText: {
    fontSize: 14,
    fontWeight: '600',
  },
  assetAI: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  aiScoreContainer: {
    alignItems: 'center',
    flex: 1,
  },
  aiScoreLabel: {
    fontSize: 11,
    color: theme.textSecondary,
    fontWeight: '500',
    marginBottom: 3,
  },
  aiScoreValue: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  recommendationContainer: {
    alignItems: 'center',
    flex: 1,
  },
  recommendationLabel: {
    fontSize: 11,
    color: theme.textSecondary,
    fontWeight: '500',
    marginBottom: 3,
  },
  recommendationValue: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  assetDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  assetDetailText: {
    fontSize: 11,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  strategyItem: {
    backgroundColor: theme.surface,
    borderRadius: 15,
    padding: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  strategyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  strategyName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.textPrimary,
    flex: 1,
  },
  strategyType: {
    backgroundColor: theme.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  strategyTypeText: {
    fontSize: 10,
    color: theme.textPrimary,
    fontWeight: '600',
  },
  strategyDescription: {
    fontSize: 14,
    color: theme.textSecondary,
    marginBottom: 10,
    lineHeight: 20,
  },
  strategyMetrics: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  metricItem: {
    alignItems: 'center',
    flex: 1,
  },
  metricLabel: {
    fontSize: 11,
    color: theme.textSecondary,
    fontWeight: '500',
    marginBottom: 3,
  },
  metricValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.textPrimary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 50,
  },
  emptyText: {
    fontSize: 16,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  fabText: {
    fontSize: 24,
    color: theme.textPrimary,
  },
});
